name: immutable_device_identifier
description: It supply device identifier for iOS / Android device. (That identifier does not change per installation)
version: 0.0.1
homepage: https://github.com/creche-studio/immutable_device_identifier

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: studio.creche.immutable_device_identifier
        pluginClass: ImmutableDeviceIdentifierPlugin
      ios:
        pluginClass: ImmutableDeviceIdentifierPlugin
